- dir_docs: !!python/unicode '/fred/oz007/ADACS/rsmith/lal_cuda/docs'
- dir_docs_api_src: !!python/unicode '/fred/oz007/ADACS/rsmith/lal_cuda/docs/src'
- dir_docs_build: !!python/unicode '/fred/oz007/ADACS/rsmith/lal_cuda/docs/_build'
- dir_python: !!python/unicode '/fred/oz007/ADACS/rsmith/lal_cuda/python'
- python_packages:
  - !!python/unicode 'lal_cuda'
- is_C_project: false
- is_Python_project: true
- version: 0.0.1
- release: 0.0.1
