- dir_docs: /Users/gpoole/my_code/ADACS-SS18A-RSmith-python/docs
- dir_docs_api_src: /Users/gpoole/my_code/ADACS-SS18A-RSmith-python/docs/src
- dir_docs_build: /Users/gpoole/my_code/ADACS-SS18A-RSmith-python/docs/_build
- dir_python: /Users/gpoole/my_code/ADACS-SS18A-RSmith-python/python
- python_packages:
  - lal_cuda
- is_C_project: false
- is_Python_project: true
- version: 0.0.1
- release: 0.0.1
