# Configure TravisCI (https://travis-ci.org) tests

language: python
env:
    # Make sure the home directory is set to be the TravisCI project directory
    - HOME=${TRAVIS_BUILD_DIR}
os:
    - linux
    - osx

# The following lines are needed by Codecov
sudo: required
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

# All the tests will be run by this Makefile
script: |
    make tests 

# Add the following lines to generate Codecov report
after_success: |
    make kcov

